### PR TITLE
0.3.2

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to v0.3.2

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
Adding a little trick to ease out installation on newer kernels. ⬆️

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Pull request merged**
