### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by astrowalker2013** [comment]
I see your update i agree with you about the  deactivate the interface instead of delete :)

**Comment by tituspijean** [comment]
If we realize there are some edge cases where the interface is not removed, we can reimplement your line of code to smite it. ;)

**Comment by astrowalker2013** [comment]
we tested a reinstallation and it's OK :) 
IT's good with new version 5.0.2 of Wireguard-UI

**Pull request merged**
